# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88074de77c876ede2157729e0dae8fdb34fc76ffd3fc32dec9863c657cd9e2c4d3391e7146e8c5e02134595ff008945b895d60fa7e35c3fd0a13a68d6eba941

test:
  secret_key_base: 86bce21403a87064e2a9780c43a954969826e48f408aee74d337d3709b2f8a70e01b918e379562b14378eb83d70f4c790f99804bf955bd0ad263d5688b429cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
